@extends('layouts.client')
@section('title','XFlow Builder - '.$workflow->name)
@push('styles')
<style>
.xflow-shell{height:calc(100vh - var(--header-height) - 42px);min-height:680px;overflow:hidden}.xflow-workspace{display:grid;grid-template-columns:240px minmax(420px,1fr) 310px;min-height:0}.xflow-panel{min-height:0;overflow:auto}.xflow-canvas-wrap{position:relative;min-width:0;min-height:0;overflow:auto;background-color:hsl(var(--muted));background-image:radial-gradient(hsl(var(--border)) 1px,transparent 1px);background-size:20px 20px}.xflow-canvas{position:relative;width:1800px;height:1100px}.xflow-lines{position:absolute;inset:0;width:100%;height:100%;pointer-events:none}.xflow-line{stroke:hsl(var(--primary));stroke-width:2;fill:none}.xflow-node{position:absolute;width:190px;min-height:86px;border:1px solid hsl(var(--border));border-radius:12px;background:hsl(var(--background));box-shadow:0 5px 18px rgba(15,23,42,.08);cursor:grab;user-select:none}.xflow-node:focus,.xflow-node.selected{outline:2px solid hsl(var(--primary));outline-offset:2px}.xflow-node.connecting{box-shadow:0 0 0 3px color-mix(in srgb,hsl(var(--primary)) 25%,transparent)}.xflow-node-head{display:flex;align-items:center;gap:9px;padding:11px;border-bottom:1px solid hsl(var(--border))}.xflow-node-body{padding:9px 11px;color:hsl(var(--muted-foreground));font-size:11px}.xflow-port{position:absolute;top:36px;width:14px;height:14px;border:2px solid hsl(var(--background));border-radius:99px;background:hsl(var(--primary));cursor:crosshair}.xflow-port.in{left:-8px}.xflow-port.out{right:-8px}.xflow-palette-item{width:100%;display:flex;gap:9px;align-items:flex-start;padding:9px;border:1px solid hsl(var(--border));border-radius:9px;text-align:left}.xflow-palette-item:hover{border-color:hsl(var(--primary));background:hsl(var(--muted))}.xflow-mobile-toggle{display:none}@media(max-width:1100px){.xflow-workspace{grid-template-columns:minmax(0,1fr)}.xflow-panel{position:absolute;z-index:20;top:0;bottom:0;width:290px;background:hsl(var(--background));box-shadow:0 10px 30px rgba(0,0,0,.15)}.xflow-palette{left:0}.xflow-inspector{right:0}.xflow-panel.is-collapsed{display:none}.xflow-mobile-toggle{display:inline-flex}}
</style>
<style>@media(max-width:1100px){.xflow-panel{display:none}.xflow-panel.is-collapsed{display:block}}</style>
@endpush
@section('content')
@php $canManage=auth()->user()->hasPermission(\App\Support\Permissions::SITES_MANAGE); @endphp
<div class="xflow-shell flex grow flex-col rounded-xl bg-background border border-input lg:ms-(--sidebar-width) mt-0 lg:mt-(--header-height) m-5">
 <form id="xflow_builder_form" method="post" action="{{ route('xflow.update',$workflow) }}" class="contents">@csrf @method('PUT')<input type="hidden" name="nodes_json" id="xflow_nodes_json"><input type="hidden" name="edges_json" id="xflow_edges_json">
  <header class="flex min-h-16 flex-wrap items-center justify-between gap-3 border-b border-input px-4 py-2"><div class="flex min-w-0 items-center gap-3"><a class="kt-btn kt-btn-sm kt-btn-icon kt-btn-ghost" href="{{ $workflow->site?route('sites.xflow.index',$workflow->site):route('xflow.index') }}"><i class="ki-filled ki-left"></i></a><div class="min-w-0"><div class="flex items-center gap-2"><input class="min-w-0 max-w-80 border-0 bg-transparent p-0 text-lg font-semibold text-mono focus:outline-none" name="name" value="{{ $workflow->name }}" maxlength="120" required><span class="kt-badge {{ $workflow->status==='active'?'kt-badge-success':'kt-badge-outline' }}">{{ ucfirst($workflow->status) }}</span></div><div class="truncate text-xs text-secondary-foreground">{{ $workflow->site?->domain ?? 'Cuenta completa' }} · {{ ucfirst($workflow->trigger_type) }}</div></div></div><div class="flex items-center gap-2"><button class="xflow-mobile-toggle kt-btn kt-btn-sm kt-btn-outline" type="button" data-toggle="palette">Nodos</button><button class="xflow-mobile-toggle kt-btn kt-btn-sm kt-btn-outline" type="button" data-toggle="inspector">Propiedades</button><select class="kt-select w-28" name="status"><option value="draft" @selected($workflow->status==='draft')>Borrador</option><option value="active" @selected($workflow->status==='active')>Activo</option><option value="paused" @selected($workflow->status==='paused')>Pausado</option></select>@if($workflow->status==='active')<button class="kt-btn kt-btn-outline" type="submit" form="xflow_run_form"><i class="ki-filled ki-to-right"></i> Probar</button>@endif @if($canManage)<button class="kt-btn kt-btn-primary" type="submit"><i class="ki-filled ki-check"></i> Guardar</button>@endif</div></header>
  @if(session('status'))<div class="border-b border-success/20 bg-success/10 px-4 py-2 text-sm text-success">{{ session('status') }}</div>@endif @if($errors->any())<div class="border-b border-danger/20 bg-danger/10 px-4 py-2 text-sm text-danger">{{ $errors->first() }}</div>@endif
  <div class="xflow-workspace relative grow">
   <aside class="xflow-panel xflow-palette border-e border-input p-3"><div class="mb-3"><div class="font-semibold text-mono">Nodos</div><p class="text-xs text-secondary-foreground">Pulsa para añadir al lienzo.</p></div>@foreach(['condition'=>'Condiciones','action'=>'Acciones'] as $type=>$title)<div class="mb-4"><div class="mb-2 text-xs font-semibold uppercase tracking-wide text-secondary-foreground">{{ $title }}</div><div class="grid gap-2">@foreach(collect($catalog)->where('type',$type) as $handler=>$definition)<button class="xflow-palette-item" type="button" data-add-node="{{ $handler }}"><span class="flex size-8 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary"><i class="ki-filled {{ $definition['icon'] }}"></i></span><span><span class="block text-xs font-medium text-mono">{{ $definition['label'] }}</span><span class="mt-1 block text-[10px] leading-4 text-secondary-foreground">{{ $definition['description'] }}</span></span></button>@endforeach</div></div>@endforeach</aside>
   <main class="xflow-canvas-wrap" id="xflow_canvas_wrap"><div class="absolute left-3 top-3 z-10 flex items-center gap-2 rounded-lg border border-input bg-background/95 px-3 py-2 text-xs text-secondary-foreground"><i class="ki-filled ki-information-2"></i><span id="xflow_hint">Arrastra nodos. Pulsa el punto derecho y después otro nodo para conectarlos.</span></div><div class="xflow-canvas" id="xflow_canvas"><svg class="xflow-lines" id="xflow_lines"></svg><div id="xflow_nodes"></div></div></main>
   <aside class="xflow-panel xflow-inspector border-s border-input p-4"><div class="mb-4"><div class="font-semibold text-mono">Propiedades</div><p class="text-xs text-secondary-foreground">Configuración del workflow y nodo seleccionado.</p></div>
    <div class="grid gap-3 border-b border-input pb-4"><label class="grid gap-1 text-xs"><span class="font-medium text-mono">Descripción</span><textarea class="kt-input min-h-20" name="description" maxlength="500">{{ $workflow->description }}</textarea></label>
     @if($workflow->trigger_type==='schedule')<label class="grid gap-1 text-xs"><span>Frecuencia</span><select class="kt-select" name="trigger_config[frequency]">@foreach($schedules as $value=>$label)<option value="{{ $value }}" @selected(($workflow->trigger_config['frequency']??'daily')===$value)>{{ $label }}</option>@endforeach</select></label><div class="grid grid-cols-3 gap-2"><label class="grid gap-1 text-xs"><span>Hora</span><input class="kt-input" type="number" min="0" max="23" name="trigger_config[hour]" value="{{ $workflow->trigger_config['hour']??2 }}"></label><label class="grid gap-1 text-xs"><span>Minuto</span><input class="kt-input" type="number" min="0" max="59" name="trigger_config[minute]" value="{{ $workflow->trigger_config['minute']??0 }}"></label><label class="grid gap-1 text-xs"><span>Día</span><input class="kt-input" type="number" min="1" max="7" name="trigger_config[weekday]" value="{{ $workflow->trigger_config['weekday']??1 }}"></label></div>@endif
     @if($workflow->trigger_type==='event')<label class="grid gap-1 text-xs"><span>Evento</span><select class="kt-select" name="trigger_config[event]">@foreach($events as $value=>$label)<option value="{{ $value }}" @selected(($workflow->trigger_config['event']??'site.updated')===$value)>{{ $label }}</option>@endforeach</select></label>@endif
     @if($workflow->trigger_type==='webhook' && $canManage)<label class="grid gap-1 text-xs"><span>URL privada</span><input class="kt-input text-[10px]" readonly value="{{ route('xflow.webhook',[$workflow,$workflow->webhook_token]) }}"></label>@elseif($workflow->trigger_type==='webhook')<p class="text-xs text-secondary-foreground">La URL privada sólo está disponible para quienes pueden administrar sitios.</p>@endif
    </div>
    <div id="xflow_empty_inspector" class="py-8 text-center text-xs text-secondary-foreground">Selecciona un nodo para editarlo.</div>
    <div id="xflow_node_inspector" class="hidden grid gap-3 pt-4"><div class="flex items-center justify-between"><span class="text-sm font-semibold text-mono" id="xflow_node_type"></span><button class="kt-btn kt-btn-sm kt-btn-icon kt-btn-ghost text-danger" type="button" id="xflow_delete_node" title="Eliminar"><i class="ki-filled ki-trash"></i></button></div><label class="grid gap-1 text-xs"><span>Etiqueta</span><input class="kt-input" id="xflow_node_label" maxlength="120"></label><div id="xflow_target_fields" class="grid gap-3"><label class="grid gap-1 text-xs"><span>Objetivo</span><select class="kt-select" id="xflow_node_target"><option value="workflow">Alcance del workflow</option>@if(!$workflow->site)<option value="site">Un sitio específico</option><option value="all">Todos los sitios</option>@endif</select></label><label class="grid gap-1 text-xs" id="xflow_node_site_field"><span>Sitio</span><select class="kt-select" id="xflow_node_site"><option value="">Seleccionar…</option>@foreach($sites as $site)<option value="{{ $site->id }}">{{ $site->domain }}</option>@endforeach</select></label></div><div id="xflow_condition_fields" class="hidden grid grid-cols-2 gap-2"><label class="grid gap-1 text-xs"><span>Operador</span><select class="kt-select" id="xflow_node_operator"><option value="equals">Es igual</option><option value="not_equals">No es igual</option></select></label><label class="grid gap-1 text-xs"><span>Valor</span><input class="kt-input" id="xflow_node_value"></label></div><div id="xflow_notify_fields" class="hidden grid gap-2"><label class="grid gap-1 text-xs"><span>Título</span><input class="kt-input" id="xflow_notify_title"></label><label class="grid gap-1 text-xs"><span>Mensaje</span><textarea class="kt-input min-h-20" id="xflow_notify_message"></textarea></label><label class="grid gap-1 text-xs"><span>Nivel</span><select class="kt-select" id="xflow_notify_level"><option value="info">Información</option><option value="success">Correcto</option><option value="warning">Aviso</option><option value="danger">Error</option></select></label></div><label class="grid gap-1 text-xs"><span>Reintentos</span><select class="kt-select" id="xflow_node_retries"><option value="0">Sin reintentos</option><option value="1">1 reintento</option><option value="2">2 reintentos</option></select></label><div class="border-t border-input pt-3"><div class="mb-2 text-xs font-medium text-mono">Conexiones salientes</div><div class="grid gap-2" id="xflow_edge_list"></div></div></div>
   </aside>
  </div>
 </form>
 <form id="xflow_run_form" method="post" action="{{ route('xflow.run',$workflow) }}">@csrf</form>
</div>
<script>
document.addEventListener('DOMContentLoaded',()=>{
 const catalog=@json($catalog),nodesRoot=document.getElementById('xflow_nodes'),canvas=document.getElementById('xflow_canvas'),svg=document.getElementById('xflow_lines');
 let nodes=@json($workflow->nodes??[]),edges=@json($workflow->edges??[]),selected=null,connecting=null,drag=null,seq=Date.now();
 const byId=id=>nodes.find(n=>n.id===id),def=n=>catalog[n.handler]||{},esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function render(){nodesRoot.innerHTML=nodes.map(n=>`<div class="xflow-node ${selected===n.id?'selected':''} ${connecting===n.id?'connecting':''}" tabindex="0" data-node="${esc(n.id)}" style="left:${n.x}px;top:${n.y}px"><button class="xflow-port in" type="button" data-input="${esc(n.id)}" aria-label="Conectar a ${esc(n.label)}"></button><div class="xflow-node-head"><span class="flex size-8 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary"><i class="ki-filled ${esc(def(n).icon||'ki-abstract-26')}"></i></span><span class="min-w-0"><span class="block truncate text-xs font-semibold text-mono">${esc(n.label)}</span><span class="block truncate text-[10px] text-secondary-foreground">${esc(def(n).label||n.handler)}</span></span></div><div class="xflow-node-body">${n.type==='condition'?'Salidas verdadero / falso':n.type==='trigger'?'Punto inicial':'Acción segura de XPanel'}</div><button class="xflow-port out" type="button" data-output="${esc(n.id)}" aria-label="Conectar desde ${esc(n.label)}"></button></div>`).join('');renderLines();renderInspector();sync();}
 function renderLines(){svg.innerHTML=edges.map(e=>{const a=byId(e.from),b=byId(e.to);if(!a||!b)return'';const x1=a.x+190,y1=a.y+43,x2=b.x,y2=b.y+43,m=(x1+x2)/2;return`<path class="xflow-line" d="M ${x1} ${y1} C ${m} ${y1}, ${m} ${y2}, ${x2} ${y2}"/><text x="${m}" y="${(y1+y2)/2-5}" fill="currentColor" font-size="10">${esc(e.branch)}</text>`}).join('')}
 function add(handler){const d=catalog[handler];if(!d)return;const id='node-'+(++seq),offset=nodes.length*25;nodes.push({id,type:d.type,handler,label:d.label,x:360+offset%700,y:120+offset%500,config:{target:'workflow',site_id:null,operator:'equals',value:'',retries:0}});selected=id;render()}
 function select(id){if(connecting&&connecting!==id){if(!edges.some(e=>e.from===connecting&&e.to===id))edges.push({from:connecting,to:id,branch:'always'});connecting=null;selected=id;render();return}selected=id;render()}
 function renderInspector(){const n=byId(selected),empty=document.getElementById('xflow_empty_inspector'),panel=document.getElementById('xflow_node_inspector');empty.classList.toggle('hidden',!!n);panel.classList.toggle('hidden',!n);if(!n)return;document.getElementById('xflow_node_type').textContent=def(n).label||n.handler;document.getElementById('xflow_node_label').value=n.label;const target=document.getElementById('xflow_node_target');target.value=n.config?.target||'workflow';document.getElementById('xflow_node_site').value=n.config?.site_id||'';document.getElementById('xflow_node_site_field').classList.toggle('hidden',target.value!=='site');document.getElementById('xflow_target_fields').classList.toggle('hidden',n.type==='trigger'||n.handler==='action.notify');document.getElementById('xflow_condition_fields').classList.toggle('hidden',n.type!=='condition');document.getElementById('xflow_node_operator').value=n.config?.operator||'equals';document.getElementById('xflow_node_value').value=n.config?.value||'';document.getElementById('xflow_notify_fields').classList.toggle('hidden',n.handler!=='action.notify');document.getElementById('xflow_notify_title').value=n.config?.title||'';document.getElementById('xflow_notify_message').value=n.config?.message||'';document.getElementById('xflow_notify_level').value=n.config?.level||'info';document.getElementById('xflow_node_retries').value=n.config?.retries||0;document.getElementById('xflow_delete_node').classList.toggle('hidden',n.type==='trigger');document.getElementById('xflow_edge_list').innerHTML=edges.filter(e=>e.from===n.id).map((e,i)=>`<div class="flex items-center gap-2"><span class="min-w-0 grow truncate text-xs">→ ${esc(byId(e.to)?.label||e.to)}</span><select class="kt-select h-8 w-24 text-xs" data-edge-branch="${esc(e.from)}|${esc(e.to)}"><option value="always" ${e.branch==='always'?'selected':''}>Siempre</option><option value="success" ${e.branch==='success'?'selected':''}>Éxito</option><option value="failure" ${e.branch==='failure'?'selected':''}>Fallo</option><option value="true" ${e.branch==='true'?'selected':''}>Verdadero</option><option value="false" ${e.branch==='false'?'selected':''}>Falso</option></select><button class="kt-btn kt-btn-sm kt-btn-icon kt-btn-ghost" type="button" data-edge-delete="${esc(e.from)}|${esc(e.to)}"><i class="ki-filled ki-cross"></i></button></div>`).join('')||'<span class="text-xs text-secondary-foreground">Sin conexiones.</span>'}
 function updateConfig(key,value){const n=byId(selected);if(!n)return;n.config=n.config||{};n.config[key]=value;sync()}
 function sync(){document.getElementById('xflow_nodes_json').value=JSON.stringify(nodes);document.getElementById('xflow_edges_json').value=JSON.stringify(edges)}
 document.querySelectorAll('[data-add-node]').forEach(b=>b.addEventListener('click',()=>add(b.dataset.addNode)));
 nodesRoot.addEventListener('pointerdown',e=>{const card=e.target.closest('[data-node]');if(!card||e.target.closest('.xflow-port'))return;select(card.dataset.node);const n=byId(card.dataset.node),rect=canvas.getBoundingClientRect();drag={id:n.id,dx:e.clientX-rect.left-n.x,dy:e.clientY-rect.top-n.y};card.setPointerCapture(e.pointerId)});
 nodesRoot.addEventListener('pointermove',e=>{if(!drag)return;const n=byId(drag.id),rect=canvas.getBoundingClientRect();n.x=Math.max(10,Math.min(1590,e.clientX-rect.left-drag.dx));n.y=Math.max(10,Math.min(990,e.clientY-rect.top-drag.dy));const card=nodesRoot.querySelector(`[data-node="${CSS.escape(n.id)}"]`);card.style.left=n.x+'px';card.style.top=n.y+'px';renderLines();sync()});
 nodesRoot.addEventListener('pointerup',()=>drag=null);nodesRoot.addEventListener('click',e=>{const out=e.target.closest('[data-output]'),input=e.target.closest('[data-input]'),card=e.target.closest('[data-node]');if(out){e.stopPropagation();connecting=out.dataset.output;selected=connecting;render()}else if(input){e.stopPropagation();select(input.dataset.input)}else if(card&&!drag)select(card.dataset.node)});
 nodesRoot.addEventListener('keydown',e=>{const card=e.target.closest('[data-node]');if(!card)return;const n=byId(card.dataset.node);if(!n)return;if(e.key==='Enter'){e.preventDefault();select(n.id);return}const movement={ArrowLeft:[-10,0],ArrowRight:[10,0],ArrowUp:[0,-10],ArrowDown:[0,10]}[e.key];if(movement){e.preventDefault();n.x=Math.max(10,Math.min(1590,n.x+movement[0]));n.y=Math.max(10,Math.min(990,n.y+movement[1]));render();nodesRoot.querySelector(`[data-node="${CSS.escape(n.id)}"]`)?.focus()}});
 document.getElementById('xflow_node_label').addEventListener('input',e=>{const n=byId(selected);if(!n)return;n.label=e.target.value;const label=nodesRoot.querySelector(`[data-node="${CSS.escape(n.id)}"] .xflow-node-head .font-semibold`);if(label)label.textContent=n.label;sync()});document.getElementById('xflow_node_target').addEventListener('change',e=>{updateConfig('target',e.target.value);renderInspector()});document.getElementById('xflow_node_site').addEventListener('change',e=>updateConfig('site_id',Number(e.target.value)||null));document.getElementById('xflow_node_operator').addEventListener('change',e=>updateConfig('operator',e.target.value));document.getElementById('xflow_node_value').addEventListener('input',e=>updateConfig('value',e.target.value));document.getElementById('xflow_notify_title').addEventListener('input',e=>updateConfig('title',e.target.value));document.getElementById('xflow_notify_message').addEventListener('input',e=>updateConfig('message',e.target.value));document.getElementById('xflow_notify_level').addEventListener('change',e=>updateConfig('level',e.target.value));document.getElementById('xflow_node_retries').addEventListener('change',e=>updateConfig('retries',Number(e.target.value)));
 document.getElementById('xflow_delete_node').addEventListener('click',()=>{const n=byId(selected);if(!n||n.type==='trigger')return;nodes=nodes.filter(x=>x.id!==selected);edges=edges.filter(e=>e.from!==selected&&e.to!==selected);selected=null;render()});document.getElementById('xflow_edge_list').addEventListener('change',e=>{if(!e.target.dataset.edgeBranch)return;const [from,to]=e.target.dataset.edgeBranch.split('|'),edge=edges.find(x=>x.from===from&&x.to===to);if(edge){edge.branch=e.target.value;sync();renderLines()}});document.getElementById('xflow_edge_list').addEventListener('click',e=>{const b=e.target.closest('[data-edge-delete]');if(!b)return;const[from,to]=b.dataset.edgeDelete.split('|');edges=edges.filter(x=>!(x.from===from&&x.to===to));render()});document.querySelectorAll('[data-toggle]').forEach(b=>b.addEventListener('click',()=>document.querySelector('.xflow-'+b.dataset.toggle).classList.toggle('is-collapsed')));document.getElementById('xflow_builder_form').addEventListener('submit',sync);render();
});
</script>
@endsection
