@extends('layouts.client')
@section('title','Ejecución XFlow - '.$run->workflow->name)
@section('content')
<div class="flex grow rounded-xl bg-background border border-input lg:ms-(--sidebar-width) mt-0 lg:mt-(--header-height) m-5"><div class="flex flex-col grow kt-scrollable-y-auto pt-5"><main class="grow"><div class="kt-container-fluid grid gap-5">
 <div class="flex flex-wrap items-end justify-between gap-3"><div><div class="text-sm text-secondary-foreground">XFlow / Ejecuciones / {{ Str::limit($run->uuid,12,'') }}</div><h1 class="text-2xl font-semibold text-mono">{{ $run->workflow->name }}</h1><p class="mt-1 text-sm text-secondary-foreground">{{ ucfirst($run->trigger) }} · {{ $run->workflow->site?->domain ?? 'Cuenta completa' }}</p></div><div class="flex gap-2"><a class="kt-btn kt-btn-outline" href="{{ route('xflow.builder',$run->workflow) }}">Abrir builder</a><span class="kt-badge {{ $run->status==='completed'?'kt-badge-success':($run->status==='failed'?'kt-badge-danger':'kt-badge-warning') }}">{{ ucfirst($run->status) }}</span></div></div>
 @if(session('status'))<div class="rounded-xl border border-success/20 bg-success/10 px-4 py-3 text-sm text-success">{{ session('status') }}</div>@endif
 <div class="grid grid-cols-2 gap-3 lg:grid-cols-4">@foreach([['Inicio',$run->started_at?->format('H:i:s')??'—'],['Duración',$run->started_at&&$run->finished_at?$run->started_at->diffInSeconds($run->finished_at).' s':'—'],['Pasos',$run->steps->count()],['Iniciado por',$run->initiator?->name??ucfirst($run->trigger)]] as [$label,$value])<div class="kt-card"><div class="kt-card-content p-4"><div class="text-xs text-secondary-foreground">{{ $label }}</div><div class="mt-1 truncate text-lg font-semibold text-mono">{{ $value }}</div></div></div>@endforeach</div>
 @if($run->error)<div class="rounded-xl border border-danger/20 bg-danger/10 px-4 py-3 text-sm text-danger">{{ $run->error }}</div>@endif
 <section class="kt-card"><div class="kt-card-header"><h2 class="kt-card-title">Trazabilidad por nodo</h2></div><div class="kt-card-content p-0"><div class="divide-y divide-input">@foreach($run->steps as $step)<article class="grid gap-3 p-4 md:grid-cols-[40px_minmax(180px,1fr)_130px_100px] md:items-center"><span class="flex size-9 items-center justify-center rounded-lg {{ $step->status==='completed'?'bg-success/10 text-success':($step->status==='failed'?'bg-danger/10 text-danger':'bg-warning/10 text-warning') }}"><i class="ki-filled {{ $step->status==='completed'?'ki-check':'ki-information-2' }}"></i></span><div class="min-w-0"><div class="font-medium text-mono">{{ $step->label }}</div><div class="text-xs text-secondary-foreground">{{ $step->handler }} · intento {{ $step->attempt }}</div>@if($step->error)<div class="mt-2 text-xs text-danger">{{ $step->error }}</div>@endif</div><span class="kt-badge justify-self-start">{{ ucfirst($step->status) }}</span><span class="text-xs text-secondary-foreground">{{ $step->duration_ms }} ms</span>@if($step->output)<details class="md:col-start-2 md:col-span-3"><summary class="cursor-pointer text-xs text-primary">Ver resultado</summary><pre class="mt-2 max-h-52 overflow-auto rounded-lg bg-muted p-3 text-[11px]">{{ json_encode($step->output,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) }}</pre></details>@endif</article>@endforeach</div></div></section>
</div></main>@include('layouts.partials.client.footer')</div></div>
@endsection
