@extends('layouts.client')

@section('title', 'Análisis - '.$site->domain)

@section('content')
<div class="flex grow rounded-xl bg-background border border-input lg:ms-(--sidebar-width) mt-0 lg:mt-(--header-height) m-5"><div class="flex flex-col grow kt-scrollable-y-auto pt-5"><main class="grow"><div class="kt-container-fluid grid gap-5">
  <div><div class="text-sm text-secondary-foreground">Análisis / {{ $site->domain }}</div><h1 class="text-2xl font-semibold text-mono">Tráfico reciente</h1><p class="mt-1 text-sm text-secondary-foreground">Resumen calculado desde las últimas {{ number_format($analytics['sampleLimit']) }} líneas del log de acceso. No usa rastreadores en el navegador.</p></div>
  <div class="grid gap-5 md:grid-cols-4"><div class="kt-card"><div class="kt-card-content p-5"><div class="text-sm text-secondary-foreground">Solicitudes</div><div class="mt-2 text-2xl font-semibold text-mono">{{ number_format($analytics['requests']) }}</div></div></div><div class="kt-card"><div class="kt-card-content p-5"><div class="text-sm text-secondary-foreground">IPs únicas</div><div class="mt-2 text-2xl font-semibold text-mono">{{ number_format($analytics['visitors']) }}</div></div></div><div class="kt-card"><div class="kt-card-content p-5"><div class="text-sm text-secondary-foreground">Transferencia</div><div class="mt-2 text-2xl font-semibold text-mono">{{ \Illuminate\Support\Number::fileSize($analytics['bytes']) }}</div></div></div><div class="kt-card"><div class="kt-card-content p-5"><div class="text-sm text-secondary-foreground">Respuestas 4xx/5xx</div><div class="mt-2 text-2xl font-semibold text-mono">{{ number_format($analytics['errors']) }}</div></div></div></div>
  <div class="grid gap-5 lg:grid-cols-2"><section class="kt-card"><div class="kt-card-header"><h2 class="kt-card-title">Rutas más solicitadas</h2></div><div class="divide-y divide-border">@forelse($analytics['topPaths'] as $path => $count)<div class="flex justify-between gap-4 px-5 py-3"><span class="truncate font-mono text-sm">{{ $path }}</span><span class="text-sm text-secondary-foreground">{{ number_format($count) }}</span></div>@empty<div class="p-8 text-center text-secondary-foreground">El log aún no contiene solicitudes analizables.</div>@endforelse</div></section><section class="kt-card"><div class="kt-card-header"><h2 class="kt-card-title">Códigos HTTP</h2></div><div class="divide-y divide-border">@forelse($analytics['statuses'] as $status => $count)<div class="flex justify-between px-5 py-3"><span class="font-mono text-sm">{{ $status }}</span><span class="text-sm text-secondary-foreground">{{ number_format($count) }}</span></div>@empty<div class="p-8 text-center text-secondary-foreground">Sin datos.</div>@endforelse</div></section></div>
  <section class="kt-card"><div class="kt-card-header"><h2 class="kt-card-title">Solicitudes recientes</h2></div><div class="overflow-x-auto"><table class="w-full min-w-[850px] text-left"><thead class="border-b border-border text-xs uppercase text-secondary-foreground"><tr><th class="px-5 py-3">IP</th><th class="px-5 py-3">Método</th><th class="px-5 py-3">Ruta</th><th class="px-5 py-3">Estado</th><th class="px-5 py-3">Bytes</th><th class="px-5 py-3">Fecha del log</th></tr></thead><tbody class="divide-y divide-border">@forelse($analytics['recent'] as $row)<tr><td class="px-5 py-3 font-mono text-sm">{{ $row['ip'] }}</td><td class="px-5 py-3 text-sm">{{ $row['method'] }}</td><td class="max-w-md truncate px-5 py-3 font-mono text-sm">{{ $row['path'] }}</td><td class="px-5 py-3">{{ $row['status'] }}</td><td class="px-5 py-3">{{ \Illuminate\Support\Number::fileSize($row['bytes']) }}</td><td class="px-5 py-3 text-sm">{{ $row['time'] }}</td></tr>@empty<tr><td colspan="6" class="px-5 py-10 text-center text-secondary-foreground">Sin solicitudes recientes.</td></tr>@endforelse</tbody></table></div></section>
</div></main>@include('layouts.partials.client.footer')</div></div>
@endsection
