@extends('layouts.client')

@section('title', 'Cron jobs - '.$site->domain)

@section('content')
<div class="flex grow rounded-xl bg-background border border-input lg:ms-(--sidebar-width) mt-0 lg:mt-(--header-height) m-5">
  <div class="flex flex-col grow kt-scrollable-y-auto pt-5"><main class="grow"><div class="kt-container-fluid grid gap-5">
    <div><div class="text-sm text-secondary-foreground">Avanzado / {{ $site->domain }}</div><h1 class="text-2xl font-semibold text-mono">Cron jobs</h1><p class="mt-1 text-sm text-secondary-foreground">Las tareas se ejecutan con el usuario de servicio sin privilegios root y escriben su salida en un log separado.</p></div>
    @if(session('status'))<div class="rounded-xl border border-success/20 bg-success/10 px-4 py-3 text-sm text-success">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="rounded-xl border border-danger/20 bg-danger/10 px-4 py-3 text-sm text-danger">{{ $errors->first() }}</div>@endif
    <div class="grid gap-5 md:grid-cols-3"><div class="kt-card"><div class="kt-card-content p-5"><div class="text-sm text-secondary-foreground">Tareas</div><div class="mt-2 text-2xl font-semibold text-mono">{{ $jobs->count() }}</div></div></div><div class="kt-card"><div class="kt-card-content p-5"><div class="text-sm text-secondary-foreground">Activas</div><div class="mt-2 text-2xl font-semibold text-mono">{{ $jobs->where('enabled', true)->count() }}</div></div></div><div class="kt-card"><div class="kt-card-content p-5"><div class="text-sm text-secondary-foreground">Log</div><div class="mt-2 text-sm font-semibold text-mono">/var/log/xpanel-host/{{ $site->domain }}-cron.log</div></div></div></div>
    @if(auth()->user()->hasPermission(\App\Support\Permissions::SITES_MANAGE))<section class="kt-card"><div class="kt-card-header"><h2 class="kt-card-title">Nueva tarea</h2></div><div class="kt-card-content p-5"><form method="post" action="{{ route('sites.cron.store', $site) }}" class="grid gap-4 md:grid-cols-[220px_1fr_auto_auto] md:items-end">@csrf<label class="grid gap-2 text-sm"><span class="font-medium text-mono">Expresión</span><input class="kt-input font-mono" name="expression" value="{{ old('expression', '0 2 * * *') }}" required></label><label class="grid gap-2 text-sm"><span class="font-medium text-mono">Comando</span><input class="kt-input font-mono" name="command" value="{{ old('command') }}" placeholder="php artisan schedule:run" maxlength="500" required></label><label class="flex items-center gap-2 pb-2 text-sm"><input type="checkbox" name="enabled" value="1" checked> Activa</label><button class="kt-btn kt-btn-primary" type="submit">Crear</button></form><p class="mt-3 text-xs text-secondary-foreground">Formato: minuto, hora, día del mes, mes y día de semana. El comando parte desde {{ $site->document_root }}.</p></div></section>@endif
    <section class="kt-card overflow-visible"><div class="kt-card-header"><h2 class="kt-card-title">Tareas configuradas</h2></div><div class="overflow-x-auto"><table class="w-full min-w-[850px] text-left"><thead class="border-b border-border text-xs uppercase text-secondary-foreground"><tr><th class="px-5 py-3">Frecuencia</th><th class="px-5 py-3">Comando</th><th class="px-5 py-3">Estado</th><th class="px-5 py-3"></th></tr></thead><tbody class="divide-y divide-border">@forelse($jobs as $job)<tr><td class="px-5 py-3 font-mono text-sm">{{ $job->expression }}</td><td class="px-5 py-3 font-mono text-sm break-all">{{ $job->command }}</td><td class="px-5 py-3"><span class="kt-badge kt-badge-outline {{ $job->enabled ? 'kt-badge-success' : '' }}">{{ $job->enabled ? 'Activa' : 'Pausada' }}</span></td><td class="px-5 py-3 text-right">@if(auth()->user()->hasPermission(\App\Support\Permissions::SITES_MANAGE))<details class="inline-block text-left"><summary class="kt-btn kt-btn-sm kt-btn-outline cursor-pointer">Editar</summary><form method="post" action="{{ route('sites.cron.update', [$site, $job]) }}" class="absolute right-10 z-20 mt-2 grid w-[36rem] max-w-[90vw] gap-3 rounded-xl border border-border bg-background p-4 shadow-lg">@csrf @method('PUT')<input class="kt-input font-mono" name="expression" value="{{ $job->expression }}" required><input class="kt-input font-mono" name="command" value="{{ $job->command }}" required><label class="flex gap-2 text-sm"><input type="checkbox" name="enabled" value="1" @checked($job->enabled)> Activa</label><button class="kt-btn kt-btn-primary" type="submit">Guardar</button></form></details><form method="post" action="{{ route('sites.cron.destroy', [$site, $job]) }}" class="inline" onsubmit="return confirm('¿Eliminar esta tarea?')">@csrf @method('DELETE')<button class="kt-btn kt-btn-sm kt-btn-outline" type="submit">Eliminar</button></form>@endif</td></tr>@empty<tr><td colspan="4" class="px-5 py-10 text-center text-secondary-foreground">Todavía no hay tareas programadas.</td></tr>@endforelse</tbody></table></div></section>
  </div></main>@include('layouts.partials.client.footer')</div>
</div>
@endsection
