@extends('layouts.client')

@section('title', 'Git - '.$site->domain)

@section('content')
<div class="flex grow rounded-xl bg-background border border-input lg:ms-(--sidebar-width) mt-0 lg:mt-(--header-height) m-5"><div class="flex flex-col grow kt-scrollable-y-auto pt-5"><main class="grow"><div class="kt-container-fluid grid gap-5">
  <div><div class="text-sm text-secondary-foreground">Avanzado / {{ $site->domain }}</div><h1 class="text-2xl font-semibold text-mono">Despliegue Git</h1><p class="mt-1 text-sm text-secondary-foreground">Publica una rama de un repositorio HTTPS público de GitHub, GitLab o Bitbucket.</p></div>
  @if(session('status'))<div class="rounded-xl border border-success/20 bg-success/10 px-4 py-3 text-sm text-success">{{ session('status') }}</div>@endif
  @if($errors->any())<div class="rounded-xl border border-danger/20 bg-danger/10 px-4 py-3 text-sm text-danger">{{ $errors->first() }}</div>@endif
  <div class="grid grid-cols-2 gap-3 lg:grid-cols-3"><div class="kt-card"><div class="kt-card-content p-4"><div class="text-xs text-secondary-foreground">Estado</div><div class="mt-1 text-lg font-semibold text-mono">{{ $repository?->status ?? 'No conectado' }}</div></div></div><div class="kt-card"><div class="kt-card-content p-4"><div class="text-xs text-secondary-foreground">Rama</div><div class="mt-1 text-lg font-semibold text-mono">{{ $repository?->branch ?? '—' }}</div></div></div><div class="kt-card"><div class="kt-card-content p-4"><div class="text-xs text-secondary-foreground">Último commit</div><div class="mt-1 text-sm font-semibold text-mono">{{ $repository?->last_commit ? substr($repository->last_commit, 0, 12) : '—' }}</div></div></div></div>
  @if($repository)<section class="kt-card"><div class="kt-card-header"><h2 class="kt-card-title">Repositorio conectado</h2></div><div class="kt-card-content p-5"><div class="grid gap-2 text-sm"><div><span class="text-secondary-foreground">Origen:</span> <code class="break-all">{{ $repository->repository_url }}</code></div><div><span class="text-secondary-foreground">Desplegado:</span> {{ $repository->deployed_at?->format('Y-m-d H:i:s') ?? 'Todavía no' }}</div>@if($repository->last_error)<div class="text-danger">{{ $repository->last_error }}</div>@endif</div>@if(auth()->user()->hasPermission(\App\Support\Permissions::SITES_MANAGE))<div class="mt-5 flex flex-wrap gap-2"><form method="post" action="{{ route('sites.git.deploy', $site) }}" onsubmit="return confirm('Se creará un backup y luego se reemplazarán los archivos administrados por Git. ¿Continuar?')">@csrf<button class="kt-btn kt-btn-primary">Desplegar último commit</button></form><form method="post" action="{{ route('sites.git.destroy', $site) }}" onsubmit="return confirm('¿Desconectar el repositorio? Los archivos publicados se conservarán.')">@csrf @method('DELETE')<button class="kt-btn kt-btn-outline">Desconectar</button></form></div>@endif</div></section>@endif
  @if(auth()->user()->hasPermission(\App\Support\Permissions::SITES_MANAGE))<section class="kt-card"><div class="kt-card-header"><h2 class="kt-card-title">{{ $repository ? 'Cambiar repositorio' : 'Conectar repositorio' }}</h2></div><div class="kt-card-content p-5"><form method="post" action="{{ route('sites.git.store', $site) }}" class="grid gap-4 lg:grid-cols-[minmax(0,1fr)_220px]">@csrf<label class="grid gap-2 text-sm"><span>URL HTTPS pública</span><input class="kt-input" type="url" name="repository_url" value="{{ old('repository_url', $repository?->repository_url) }}" placeholder="https://github.com/organizacion/proyecto.git" required></label><label class="grid gap-2 text-sm"><span>Rama</span><input class="kt-input font-mono" name="branch" value="{{ old('branch', $repository?->branch ?? 'main') }}" required></label><label class="grid max-w-xs gap-2 text-sm lg:col-span-2"><span>Escribe DEPLOY para confirmar el reemplazo</span><input class="kt-input font-mono" name="confirmation" autocomplete="off" required></label><p class="text-xs text-secondary-foreground lg:col-span-2">Se conservan <code>.env</code>, desafíos ACME, páginas de error y sesiones. Los symlinks y repositorios privados no se aceptan en esta primera implementación.</p><div class="flex justify-end lg:col-span-2"><button class="kt-btn kt-btn-primary">Conectar y desplegar</button></div></form></div></section>@endif
</div></main>@include('layouts.partials.client.footer')</div></div>
@endsection
