@extends('layouts.client')
@section('title', 'Acceso SSH - '.$site->domain)
@section('content')
<div class="flex grow rounded-xl bg-background border border-input lg:ms-(--sidebar-width) mt-0 lg:mt-(--header-height) m-5"><div class="flex flex-col grow kt-scrollable-y-auto pt-5"><main class="grow"><div class="kt-container-fluid grid gap-5">
<div><div class="text-sm text-secondary-foreground">Avanzado / {{ $site->domain }}</div><h1 class="text-2xl font-semibold text-mono">Acceso SSH</h1><p class="mt-1 text-sm text-secondary-foreground">Terminal aislada por permisos Unix y autenticada exclusivamente mediante llaves públicas.</p></div>
@if(session('status'))<div class="rounded-xl border border-success/20 bg-success/10 px-4 py-3 text-sm text-success">{{ session('status') }}</div>@endif @if($errors->any())<div class="rounded-xl border border-danger/20 bg-danger/10 px-4 py-3 text-sm text-danger">{{ $errors->first() }}</div>@endif
<div class="grid gap-5 md:grid-cols-3">@foreach([['Estado',$settings->ssh_enabled?'Activo':'Inactivo'],['Usuario',$site->systemUser()],['Llaves',$sshKeys->count()]] as [$label,$value])<div class="kt-card"><div class="kt-card-content p-5"><div class="text-sm text-secondary-foreground">{{ $label }}</div><div class="mt-2 font-semibold text-mono">{{ $value }}</div></div></div>@endforeach</div>
@if(auth()->user()->hasPermission(\App\Support\Permissions::SITES_MANAGE))<section class="kt-card"><div class="kt-card-header"><h2 class="kt-card-title">Estado de la terminal</h2></div><div class="kt-card-content p-5"><form method="post" action="{{ route('sites.access.update',$site) }}" class="grid gap-4">@csrf @method('PUT')<input type="hidden" name="sftp_enabled" value="{{ $settings->sftp_enabled?1:0 }}"><input type="hidden" name="ftp_enabled" value="{{ $settings->ftp_enabled?1:0 }}"><label class="flex items-center gap-2"><input type="checkbox" name="ssh_enabled" value="1" @checked($settings->ssh_enabled)> Permitir terminal SSH por llaves</label><p class="text-xs text-secondary-foreground">La contraseña permanece prohibida para terminal. Se desactivan forwarding TCP, X11, túneles y gateway ports.</p><button class="kt-btn kt-btn-primary w-fit" @disabled($sshKeys->isEmpty() && !$settings->ssh_enabled)>Guardar estado</button></form></div></section>
<section class="kt-card"><div class="kt-card-header"><h2 class="kt-card-title">Añadir llave pública</h2></div><div class="kt-card-content p-5"><form method="post" action="{{ route('sites.access.keys.store',$site) }}" class="grid gap-4">@csrf<label class="grid gap-2 text-sm"><span>Nombre</span><input class="kt-input max-w-md" name="name" required maxlength="80" placeholder="Portátil personal"></label><label class="grid gap-2 text-sm"><span>Llave Ed25519 o RSA</span><textarea class="kt-textarea min-h-28 font-mono" name="public_key" required placeholder="ssh-ed25519 AAAA... usuario@equipo"></textarea></label><button class="kt-btn kt-btn-primary w-fit">Añadir llave</button></form></div></section>@endif
<section class="kt-card"><div class="kt-card-header"><h2 class="kt-card-title">Llaves autorizadas</h2></div><div class="divide-y divide-border">@forelse($sshKeys as $key)<div class="flex items-center justify-between gap-4 p-5"><div><div class="font-semibold text-mono">{{ $key->name }}</div><div class="mt-1 text-xs text-secondary-foreground">{{ $key->fingerprint }}</div><div class="mt-1 max-w-3xl truncate text-xs text-secondary-foreground">{{ $key->public_key }}</div></div>@if(auth()->user()->hasPermission(\App\Support\Permissions::SITES_MANAGE))<form method="post" action="{{ route('sites.access.keys.destroy',[$site,$key]) }}">@csrf @method('DELETE')<button class="kt-btn kt-btn-sm kt-btn-outline">Retirar</button></form>@endif</div>@empty<div class="p-8 text-center text-secondary-foreground">No hay llaves SSH.</div>@endforelse</div></section>
<div class="rounded-xl border border-border p-4 text-sm">Conexión: <code>ssh {{ $site->systemUser().'@'.request()->getHost() }}</code></div>
</div></main></div></div>
@endsection
